#ansible-playbook test-playbook.yml --extra-vars "ansible_become_pass=sudo_pass"
#To run without installing software dependencies
#ansible-playbook test-playbook.yml --extra-vars "ansible_become_pass=sudo_pass" --skip-tags "software"
- hosts: localhost

  pre_tasks:
     - raw:  ansible-galaxy role install -r requirements.yml

  vars:
    dict_common_create_user:
      xussof:
        user_name: xussof
        user_shell: /bin/bash
        user_home: /home/xussof
        is_sudo: True


  tasks:
    - name: Including role to test
      include_role:
        name: '../common_create-user'
